全社用簡易Webページ対応（デプロイエラーが発生しないかの確認）
[API配置についてのルール]
1. ローカル環境は, app/api をベース(GitHubにアップロードしない)
2. 本番環境を想定したデプロイは, local/api をベース(GitHubにアップロードする → 以下のエラーが出たため, NG)
→ Lambda(本番環境)が使えるようになったら, フォルダ構成は改めて考える

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
   Collecting page data ...
Error: export const dynamic = "force-static"/export const revalidate not configured on route "/local/api/delivery-site" with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
    at 62755 (.next/server/app/local/api/delivery-site/route.js:1:2667)
    at c (.next/server/webpack-runtime.js:1:128)
    at <unknown> (.next/server/app/local/api/delivery-site/route.js:1:8616)
    at c.X (.next/server/webpack-runtime.js:1:1206)
    at <unknown> (.next/server/app/local/api/delivery-site/route.js:1:8594)
    at Object.<anonymous> (.next/server/app/local/api/delivery-site/route.js:1:8648)

> Build error occurred
[Error: Failed to collect page data for /local/api/delivery-site] {
  type: 'Error'
}