全社用簡易Webページ対応（ESLint の コメント追記, Deployエラー対策） // eslint-disable-next-line @typescript-eslint/no-require-imports
------------------------------------------------------------------------------------------------------
./src/lib/sendMail.ts
3:20  Error: A `require()` style import is forbidden.  @typescript-eslint/no-require-imports

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
Error: Process completed with exit code 1.
------------------------------------------------------------------------------------------------------