全社用簡易Webページ対応（デプロイエラーが発生しないかの確認）
フォルダ移動(app/local/api), フォルダ名変更(app/local-api)では, エラーが出てしまうので,
apiフォルダは, GitHubに持って行っていけないことが分かった

[API配置についてのルール]
1. ローカル環境は, app/api を使用
2. 本番環境は, app/api を削除の上デプロイ(GitHubにアップロードしない)
→ Lambda(本番環境)が使えるようになったら, フォルダ構成は改めて考える

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
   Collecting page data ...
Error: export const dynamic = "force-static"/export const revalidate not configured on route "/local/api/delivery-site" with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
    at 62755 (.next/server/app/local/api/delivery-site/route.js:1:2667)
    at c (.next/server/webpack-runtime.js:1:128)
    at <unknown> (.next/server/app/local/api/delivery-site/route.js:1:8616)
    at c.X (.next/server/webpack-runtime.js:1:1206)
    at <unknown> (.next/server/app/local/api/delivery-site/route.js:1:8594)
    at Object.<anonymous> (.next/server/app/local/api/delivery-site/route.js:1:8648)

> Build error occurred
[Error: Failed to collect page data for /local/api/delivery-site] {
  type: 'Error'
}
Error: Process completed with exit code 1.

Error: export const dynamic = "force-static"/export const revalidate not configured on route "/local-api/inbound-history" with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
    at 67099 (.next/server/app/local-api/inbound-history/route.js:1:3016)
    at c (.next/server/webpack-runtime.js:1:128)
    at <unknown> (.next/server/app/local-api/inbound-history/route.js:1:8863)
    at c.X (.next/server/webpack-runtime.js:1:1206)
    at <unknown> (.next/server/app/local-api/inbound-history/route.js:1:8841)
    at Object.<anonymous> (.next/server/app/local-api/inbound-history/route.js:1:8895)
Error: export const dynamic = "force-static"/export const revalidate not configured on route "/local-api/delivery-site" with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
    at 82445 (.next/server/app/local-api/delivery-site/route.js:1:2997)
    at c (.next/server/webpack-runtime.js:1:128)
    at <unknown> (.next/server/app/local-api/delivery-site/route.js:1:8613)
    at c.X (.next/server/webpack-runtime.js:1:1206)
    at <unknown> (.next/server/app/local-api/delivery-site/route.js:1:8591)
    at Object.<anonymous> (.next/server/app/local-api/delivery-site/route.js:1:8645)
> Build error occurred
[Error: Failed to collect page data for /local-api/inbound-history] {
  type: 'Error'
}
Error: Process completed with exit code 1.