全社用簡易Webページ対応（apiHandler廃止, デプロイエラーが発生しないかの確認）
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
   Collecting page data ...
Error: export const dynamic = "force-static"/export const revalidate not configured on route "/api/delivery-site/[deliverySiteId]" with "output: export". See more info here: https://nextjs.org/docs/advanced-features/static-html-export
    at 9947 (.next/server/app/api/delivery-site/[deliverySiteId]/route.js:1:1247)
    at c (.next/server/webpack-runtime.js:1:128)
    at <unknown> (.next/server/app/api/delivery-site/[deliverySiteId]/route.js:1:8871)
    at c.X (.next/server/webpack-runtime.js:1:1206)
    at <unknown> (.next/server/app/api/delivery-site/[deliverySiteId]/route.js:1:8849)
    at Object.<anonymous> (.next/server/app/api/delivery-site/[deliverySiteId]/route.js:1:8902)